### ISSUE TITLE
Can't view all suggestions in search

### ISSUE THREAD

**Issue by yinleon** [biglocalnews/usps#17]
When searching for geographies to sample, the suggestions are not scrollable so you only see about 5 even when there are most in the list.

<img width="1367" alt="Screenshot 2023-02-26 at 5 00 40 PM" src="https://user-images.githubusercontent.com/7376699/221440054-222b27c2-c437-4d29-b47f-a332ffff93d7.png">

**Comment by jnu** [comment]
I see what you mean. I need to both add scrolling and compute height dynamically to fit on screen.

Worth noting we still only ever fetch the top 10 results from the DB.
